"""
NJZ eSports API Schemas — Pydantic v2 Models

This package contains all canonical Pydantic schemas for the NJZ eSports platform,
mirroring the TypeScript type definitions in data/schemas/*.ts.

SCHEMA CHANGE: Initial definition — 2026-03-27
"""

# GameNodeID Hierarchy
from .game_node import (
    QuarterKey,
    TeZeTRoute,
    TeZeTContentType,
    TeZeTBranch,
    GameQuarterVariant,
    QuarterConfig,
    QuarterGrid,
    BaseGameNodeID,
    ValorantEconomy,
    ValorantNodeData,
    GameNodeIDValorant,
    CS2Economy,
    CS2NodeData,
    GameNodeIDCS2,
    GameNodeID,
    WorldPort,
    TeZeT,
    SupportedGame,
)

# TeneT Protocol
from .tenet import (
    TrustLevel,
    DataSourceType,
    DATA_SOURCE_TRUST,
    VerificationStatus,
    DistributionPath,
    ConfidenceSourceContribution,
    ConfidenceScore,
    ManualReviewRecord,
    TenetVerificationResult,
    TenetVerificationRequest,
    SourceDataPayload,
    DataTierRequirement,
    TenetDirectoryEntry,
    LiveEventType,
    MatchScorePayload,
    RoundUpdatePayload,
    MatchEndPayload,
    PathALiveEvent,
    LegacyRoundPlayerStat,
    LegacyRoundRecord,
    TeamEconomyState,
    EconomyLogEntry,
    PlayerPositionSnapshot,
    MinimapFrame,
    VideoReviewGrade,
    PathBLegacyRecord,
)

# Live Data
from .live_data import (
    WebSocketStatus,
    WebSocketState,
    LiveMatchStatus,
    LiveTeamView,
    LiveMatchView,
    LivePlayerStats,
    LiveRoundSummary,
    LiveTeamEconomy,
    LiveEconomySnapshot,
    WsMessageType,
    WsMessage,
    WsMatchStartMessage,
    WsScoreUpdateMessage,
    WsRoundEndMessage,
    WsPlayerStatsMessage,
    WsEconomyMessage,
    WsMatchEndMessage,
    WsHeartbeatMessage,
    WsErrorMessage,
)

# Legacy Data
from .legacy_data import (
    PaginatedResponse,
    ApiResponse,
    MatchTeamRef,
    VerifiedMatchSummary,
    VerifiedRoundPlayerStat,
    VerifiedRoundRecord,
    VerifiedTeamEconomy,
    VerifiedEconomyEntry,
    VerifiedMatchDetail,
    PlayerMatchPerformance,
    PlayerSeasonStats,
    TournamentRecord,
    SimRatingComponents,
    SimRatingEntry,
)

__all__ = [
    # GameNodeID hierarchy
    "QuarterKey",
    "TeZeTRoute",
    "TeZeTContentType",
    "TeZeTBranch",
    "GameQuarterVariant",
    "QuarterConfig",
    "QuarterGrid",
    "BaseGameNodeID",
    "ValorantEconomy",
    "ValorantNodeData",
    "GameNodeIDValorant",
    "CS2Economy",
    "CS2NodeData",
    "GameNodeIDCS2",
    "GameNodeID",
    "WorldPort",
    "TeZeT",
    "SupportedGame",
    # TeneT Protocol
    "TrustLevel",
    "DataSourceType",
    "DATA_SOURCE_TRUST",
    "VerificationStatus",
    "DistributionPath",
    "ConfidenceSourceContribution",
    "ConfidenceScore",
    "ManualReviewRecord",
    "TenetVerificationResult",
    "TenetVerificationRequest",
    "SourceDataPayload",
    "DataTierRequirement",
    "TenetDirectoryEntry",
    "LiveEventType",
    "MatchScorePayload",
    "RoundUpdatePayload",
    "MatchEndPayload",
    "PathALiveEvent",
    "LegacyRoundPlayerStat",
    "LegacyRoundRecord",
    "TeamEconomyState",
    "EconomyLogEntry",
    "PlayerPositionSnapshot",
    "MinimapFrame",
    "VideoReviewGrade",
    "PathBLegacyRecord",
    # Live Data
    "WebSocketStatus",
    "WebSocketState",
    "LiveMatchStatus",
    "LiveTeamView",
    "LiveMatchView",
    "LivePlayerStats",
    "LiveRoundSummary",
    "LiveTeamEconomy",
    "LiveEconomySnapshot",
    "WsMessageType",
    "WsMessage",
    "WsMatchStartMessage",
    "WsScoreUpdateMessage",
    "WsRoundEndMessage",
    "WsPlayerStatsMessage",
    "WsEconomyMessage",
    "WsMatchEndMessage",
    "WsHeartbeatMessage",
    "WsErrorMessage",
    # Legacy Data
    "PaginatedResponse",
    "ApiResponse",
    "MatchTeamRef",
    "VerifiedMatchSummary",
    "VerifiedRoundPlayerStat",
    "VerifiedRoundRecord",
    "VerifiedTeamEconomy",
    "VerifiedEconomyEntry",
    "VerifiedMatchDetail",
    "PlayerMatchPerformance",
    "PlayerSeasonStats",
    "TournamentRecord",
    "SimRatingComponents",
    "SimRatingEntry",
]
